import { inputFieldType } from "../_types/inputFieldType";
export const fieldsObject: inputFieldType[] = [
  {
    type: "email",
    name: "email",
    lable: "Email",
    fullWidth: true,
    required: true,
    placeholder: "mostafa@gmail.com",
  },
  {
    type: "text",
    name: "firstName",
    lable: "First Name",
    fullWidth: false,
    required: true,
    placeholder: "Mostafa",
  },
  {
    type: "text",
    name: "lastName",
    lable: "Last Name",
    fullWidth: false,
    required: true,
    placeholder: "Ahmed",
  },
  {
    type: "dropdown",
    name: "country",
    lable: "Country",
    fullWidth: false,
    required: true,
    placeholder: "",
    options: [],
  },
  {
    type: "dropdown",
    name: "city",
    lable: "City/State",
    placeholder: "",
    fullWidth: false,
    required: true,
    dependency: "country",
  },
  {
    type: "text",
    name: "address",
    lable: "Address",
    placeholder: "123 main st.",
    required: true,
    fullWidth: true,
  },
  {
    type: "phone",
    name: "phone1",
    lable: "Phone Number 1",
    fullWidth: false,
    required: true,
    placeholder: "(02) 11xxxxxxxx",
  },
  {
    type: "phone",
    name: "phone2",
    lable: "Phone Number 2",
    fullWidth: false,
    required: false,
    placeholder: "(02) 11xxxxxxxx",
  },
];
