const colorArray = [
  { colorString: "silver", colorHex: "#C0C0C0" },
  { colorString: "white", colorHex: "#FFFFFF" },
  { colorString: "white", colorHex: "#FFFFFF" },
  { colorString: "white", colorHex: "#FFFFFF" },
  { colorString: "sand gold", colorHex: "#C2B280" },
  { colorString: "Blue", colorHex: "#0000FF" },
  { colorString: "Black", colorHex: "#000000" },
  { colorString: "Lavender", colorHex: "#E6E6FA" },
  { colorString: "gray", colorHex: "#808080" },
  { colorString: "White", colorHex: "#FFFFFF" },
  { colorString: "Burgundy", colorHex: "#800020" },
  { colorString: "steel blue", colorHex: "#4682B4" },
  { colorString: "Smoky Teal", colorHex: "#5F8A8B" },
  { colorString: "Blue", colorHex: "#0000FF" },
  { colorString: "Deep Purple", colorHex: "#673AB7" },
  { colorString: "Golden", colorHex: "#FFD700" },
  { colorString: "Green", colorHex: "#008000" },
  { colorString: "Noir Black", colorHex: "#000000" },
  { colorString: "Meteorite Black", colorHex: "#4A4A4A" },
  { colorString: "Aqua Green", colorHex: "#00FFBF" },
  { colorString: "Matte Black", colorHex: "#282828" },
  { colorString: "Black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "Green", colorHex: "#008000" },
  { colorString: null, colorHex: null },
  { colorString: null, colorHex: null },
  { colorString: "White", colorHex: "#FFFFFF" },
  { colorString: "blue", colorHex: "#0000FF" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "White", colorHex: "#FFFFFF" },
  { colorString: "Taupe", colorHex: "#483C32" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "blue", colorHex: "#0000FF" },
  { colorString: "white", colorHex: "#FFFFFF" },
  { colorString: "Blue", colorHex: "#0000FF" },
  { colorString: "White", colorHex: "#FFFFFF" },
  { colorString: null, colorHex: null },
  { colorString: "Blue", colorHex: "#0000FF" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "white", colorHex: "#FFFFFF" },
  { colorString: "Black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "Pink", colorHex: "#FFC0CB" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "dark steel silver", colorHex: "#708090" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "carbon silver", colorHex: "#A9A9A9" },
  { colorString: "Ceramic Black", colorHex: "#1C1C1C" },
  { colorString: "Black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "Pebble Grey", colorHex: "#B0B0B0" },
  { colorString: "Metallic Grey", colorHex: "#A0A0A0" },
  { colorString: "Metallic Grey", colorHex: "#A0A0A0" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "Dark Iron Gray", colorHex: "#525252" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "grey", colorHex: "#808080" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "grey", colorHex: "#808080" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "ceremic black", colorHex: "#1C1C1C" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "Blue", colorHex: "#0000FF" },
  { colorString: "Green", colorHex: "#008000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "grey", colorHex: "#808080" },
  { colorString: "grey", colorHex: "#808080" },
  { colorString: "grey", colorHex: "#808080" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "white", colorHex: "#FFFFFF" },
  { colorString: "white", colorHex: "#FFFFFF" },
  { colorString: "white", colorHex: "#FFFFFF" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "blue", colorHex: "#0000FF" },
  { colorString: "silver", colorHex: "#C0C0C0" },
  { colorString: "steel grey", colorHex: "#708090" },
  { colorString: "blue", colorHex: "#0000FF" },
  { colorString: "silver", colorHex: "#C0C0C0" },
  { colorString: "white", colorHex: "#FFFFFF" },
  { colorString: "blue", colorHex: "#0000FF" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "grey", colorHex: "#808080" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "steel grey", colorHex: "#708090" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "Blue", colorHex: "#0000FF" },
  { colorString: "black", colorHex: "#000000" },
  { colorString: "grey", colorHex: "#808080" },
  { colorString: "silver", colorHex: "#C0C0C0" },
  { colorString: "black", colorHex: "#000000" },
];

export const colorMap: Map<string | null, string | null> = new Map(
  colorArray.map((item) => [item.colorString, item.colorHex])
);
